---
# Power Restoration Automation Playbook
# Targets: Core switches/routers after UPS power-on signal
- name: "POST-BLACKOUT RECOVERY PROTOCOL"
  hosts: network_core
  vars:
    backup_dir: "/mnt/network_backups"
    
  tasks:
    # Phase 1: Configuration Rollback
    - name: "RESTORE LAST KNOWN GOOD CONFIG"
      cisco.ios.ios_config:
        src: "{{ backup_dir }}/{{ inventory_hostname }}_golden.cfg"
        save_when: modified
      tags: critical

    # Phase 2: Interface Validation
    - name: "ENABLE CRITICAL INFRASTRUCTURE PORTS"
      cisco.ios.ios_interface:
        name: "{{ item }}"
        state: up
        duplex: full
        speed: auto
      loop: "{{ core_interfaces }}"
      when: ansible_network_os == 'ios'
